### ISSUE TITLE
Default map view

### ISSUE THREAD

**Issue by fridayshoes** [DHoffm/Responsive-color-google-map#4]
Is it possible to add an option in the backend to set the default view type between Map or Satellite?

**Comment by DHoffm** [comment]
I'm not sure what your question is! The module got an option called "Map Type" and you can switch it to one of the following: Roadmap,Satellite, Hybrid, Terrain
This is the default.

**Comment by fridayshoes** [comment]
The map type control only has the option ON or OFF in the backend? Where is option for Roadmap, Satellite, Hybrid and Terrain?

**Comment by DHoffm** [comment]
The field definition can be found here: https://github.com/DHoffm/Responsive-color-google-map/blob/master/mod_profil_responsive_map.xml

<field name="profilResponsiveMapType" type="radio" default="0" label="MOD_PROFIL_RESPONSIVE_MAP_TYPE" description="">
          <option value="0">MOD_PROFIL_RESPONSIVE_MAP_TYPE_ROADMAP</option>
          <option value="1">MOD_PROFIL_RESPONSIVE_MAP_TYPE_SATELLITE</option>
          <option value="2">MOD_PROFIL_RESPONSIVE_MAP_TYPE_HYBRID</option>
          <option value="3">MOD_PROFIL_RESPONSIVE_MAP_TYPE_TERRAIN</option>
        </field>

**Comment by fridayshoes** [comment]
Ah cool, yes I see what to do. Thanks

**Comment by fridayshoes** [comment]
I just realised the version on here is newer than the one on the Joomla extension page, I see the option in the backend now :)

**Comment by DHoffm** [comment]
Yeah I don't had much time over the last half year to keep up the development. Sorry that I forgot to mention that the repo version is newer. If you plan to extend the plugin you might fork the repo and your changes can be merged in later.
